### ISSUE TITLE
Restore tabs discarded

### ISSUE THREAD

**Issue by Mrfiregem** [XFox111/ChromiumTabsAside#10]
Right now when a group is restored, every tab is loaded at once. It'd be better if they were brought back discarded and only loaded when the tab is opened by the user.

**Comment by XFox111** [comment]
Unfortunately, I have no ideas how to implement this feature. The problem is when a tab is restored, its actual URL is `target:blank`. And if I discard tab immediately after its creation, it will remain blank. And Chrome Extension API doesn't allow create tabs without initial loading

**Comment by AmineI** [comment]
> Unfortunately, I have no ideas how to implement this feature. The problem is when a tab is restored, its actual URL is `target:blank`. And if I discard tab immediately after its creation, it will remain blank. And Chrome Extension API doesn't allow create tabs without initial loading

Discarding in an [onUpdated](https://developer.chrome.com/extensions/tabs#event-onUpdated) event listener works (discarding the tab as soon as the url gets updated from `target:blank` to the actual url). 

For example, this creates a google tab, discarded before it even starts loading.
```
chrome.tabs.create({ url:"https://google.fr" }, tab => {
    chrome.tabs.onUpdated.addListener(function listener(tabId) {
        if (tabId === tab.id) {
            chrome.tabs.onUpdated.removeListener(listener);
            chrome.tabs.discard(tabId);
        }
    });
});
```

There are most likely a few quirks to deal with to use this here though, like not discarding the one tab that actually gets active. 

I'll try to figure it out and submit a PR, but I'm new to this project (discovered it yesterday) so I have some exploration to do beforehand ! Don't hesitate to use this piece of code if you have a lightbulb moment before I do :)

**Comment by XFox111** [comment]
Thanks for using my extension. I appreciate it) 

Feature has been implemented and new version will be submitted as soon as the previous one will be approved by webstores. It will take some time. For now, you can download [v1.4 preview version from GitHub Releases](https://github.com/XFox111/ChromiumTabsAside/releases/tag/v1.4) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version
