### ISSUE TITLE
Broken pane CSS on gaana.com

### ISSUE THREAD

**Issue by XFox111** [XFox111/ChromiumTabsAside#13]
Reported by reddit user
![Annotation 2020-06-21 094836](https://user-images.githubusercontent.com/28831743/85234279-e571af80-b414-11ea-8275-f96140236551.jpg)

Solution: improve the pane's CSS to override website's values

Hint: [User CSS](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb) extension has similar implementation. So it's codebase may be useful

**Comment by AmineI** [comment]
You could use inject an iframe to host the pane.
It has a few benefits :

- CSS stylesheets are local to the frame, they aren't impacted by the host website, and vice versa, thus solving this issue for any website
- You will be able to use the same TabsAside.html for both the in-page pane (in an iframe) and the full page tabs aside . Same for the JS; thus eliminating most of the current duplicate code, which will get harder and harder to maintain. 

It can be though to set up (especially the size of the iframe usually), but I think it could be worth it.

**Comment by AmineI** [comment]
```
var pane = document.createElement('iframe');
pane.src = chrome.extension.getURL('TabsAside.html');
pane.style="position: fixed; height: 100%;width: 43%;right: 0;top: 0;z-index:9999"
document.body.appendChild(pane);
```
This little snippet can easily get you started : run it from a content script on a page. I can confirm it works on gaana.com without any changes to the CSS. Not sure which way to go to add the opening animation and darken the rest of the page, though.
