### ISSUE TITLE
Saving TabsAside "session" to a Collection in Edge Chromium

### ISSUE THREAD

**Issue by Xtremis77** [XFox111/ChromiumTabsAside#15]
This is more of an idea, but it would be great if I could save a TabsAside session straight into a new Collection in Edge Chromium. It's great to be able to save to Favorites, but to send to a Collection would be really useful too :)
Not sure how easy it would be to implement, since the Collections feature doesn't exist in Chrome.
Thanks!

**Comment by XFox111** [comment]
If you want to add opened tabs into collection you can right-click any opened tab and press "Add all tabs to a new collection"
![image](https://user-images.githubusercontent.com/28831743/85447822-b5eeae80-b59e-11ea-8fdd-1b0dfa93db01.png)

**Comment by Xtremis77** [comment]
Ah perfect! :) I'll close this "issue" then, thanks!

**Comment by XFox111** [comment]
You're welcome :)
