### ISSUE TITLE
No icons for buttons & delete button misclick

### ISSUE THREAD

**Issue by saching13** [XFox111/ChromiumTabsAside#17]
I was going over the extension and I check the delete accidentally since I dint knew what that button would do since it doesn't come with any name or wordings. it's just a check box. is it possible to fix it ? and it would be great if you can suggest if there is a way to get it back

![image](https://user-images.githubusercontent.com/43363595/85899693-4998c880-b7b3-11ea-8282-c415f32e332a.png)

Thank you

**Comment by XFox111** [comment]
Hi. Thanks for your feedback. Could you please provide following information:
- OS name and version
- Browser name and version

**Comment by saching13** [comment]
Mac OS 10.15.5
Browser Edge Version 83.0.478.56

**Comment by XFox111** [comment]
Yes. I'm aware of this issue (see issue #11). The problem is that the extension uses Segoe MDL2 Assets and Segoe UI fonts which are preinstalled only on Windows OS. I'll fix this on next update. Until then, you can manually install this fonts into your system.

**Comment by AmineI** [comment]
> I was going over the extension and I check the delete accidentally

Actually, that's a good point regardless of the font issue.
Perhaps it would be better to add a prompt or alert to confirm the deletion @XFox111 ? Misclicks happen, even more with touch devices, so a prompt would help prevent losing quite a lot of data

> If there is a way to get it back

Not yet I'm afraid @saching13 .

**Comment by XFox111** [comment]
> Perhaps it would be better to add a prompt or alert to confirm the deletion

Yep. This is what I'm going to do

**Comment by saching13** [comment]
that would be great :)

**Comment by XFox111** [comment]
@saching13, hi. Could you please test [this preview version](https://github.com/XFox111/ChromiumTabsAside/releases/tag/v1.5-preview) of the extension? I've checked it on my machine and it works. So I'd like to make sure that it works on MacOS as well. If everything's ok, I complete the PR and publish this version on the webstores

**Note** that sideloaded extensions don't replace officially installed ones so there's no any risk

**Comment by saching13** [comment]
Sure. I will check it and get back to you. :)

**Comment by saching13** [comment]
Seems to be working fine. Awesome. Thank you
![image](https://user-images.githubusercontent.com/43363595/86392110-c44c6280-bc4f-11ea-8175-81e530b27095.png)
![image](https://user-images.githubusercontent.com/43363595/86392124-cadada00-bc4f-11ea-8ba5-063ff7a2f847.png)

**Comment by XFox111** [comment]
Thanks for using my extension. I appreciate it) 

I've just done a new version and submitted it to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin) and [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd). It will take some time to pass the validation process. For now, you can download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version
