### ISSUE TITLE
Ability to save tabs on toolbar icon click

### ISSUE THREAD

**Issue by SOI7** [XFox111/ChromiumTabsAside#22]
First of all, the extension works greatly and I still don't get why Microsoft isn't adding this feature yet, not even as a Collections subfunction. That said, there's only one grip I have with it, and it's the extra step required to set tabs aside, compared to the legacy Edge. 
In fact, in the old Edge you could just click on the toolbar button and all your open tabs would be set aside immediately, while on this extension you need to summon the menu first and the click on "Set current tabs aside". 
While I understand that some people may want more control, and since I don't know the limitations of Chromium extensions, I'm gonna throw this idea: an option/toggle, in the ellipsis menu of the extension, to set all tabs aside on click. This way, people who want to use the old behavior can activate it without forcing the function on others.
Possible limitations:
-The toggle could interfere with the restore menu/tab. A condition check could be investigated but, again, I'm no expert on extensions
-Chromium extensions may not allow actions on click (I think?). In that case, a keyboard shortcut as you suggested on Reddit may do the trick, I believe
-The toggle could hide the other sub-options. To avoid that, you may summon them by right-clicking the button

**Comment by XFox111** [comment]
> an option/toggle, in the ellipsis menu of the extension, to set all tabs aside on click

So you want to set tabs aside on left-click and open the pane on right-click on the extension icon? If it so, I can do this but there's still quite the same issue: right-clicking the extension icon in any way will open standard extension context menu. I can add an option to this menu (e.g. to set tabs aside you click on the extension icon, to open the pane you right-click the icon and choose "Open the pane" or so). And in this way there's still a 2-step action - either it's the pane opening or  settings tabs aside

Ok. Maybe I've not quite clear caught your idea. Let's say, I've made the extension icon set tabs aside on click instead opening the pane. What's the best way to open the pane in this situation?

**Comment by SOI7** [comment]
This tricky issue comes because the Legacy Edge had two dedicated buttons for setting the tabs aside and to open the pane, while with the extension you have to rely on a single button. Anyway, the solution you suggested (left click to set tabs aside, right click to show the menu and open the pane from there) seems quite reasonable to me. I'd suggest you to make this feature optional, though, because probably some people prefer the current implementation

**Comment by XFox111** [comment]
Ok. I'll do this for the next update. Stay tuned

**Comment by XFox111** [comment]
@SOI7, hi. Could you please test [this preview version](https://github.com/XFox111/ChromiumTabsAside/releases/tag/v1.6-preview) of the extension? Is it what you wanted?

**Note** that sideloaded extensions don't replace officially installed ones so there's no any risk

**Comment by SOI7** [comment]
Just tested, it works exactly as intended! Excellent job!

**Comment by XFox111** [comment]
Thanks for using my extension. I appreciate it) 

I've just done a new version and submitted it to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin) and [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd). It will take some time to pass the validation process.
