### ISSUE TITLE
MacOS shortcut bindings interfering

### ISSUE THREAD

**Issue by saching13** [XFox111/ChromiumTabsAside#27]
### Description
Moves all my tabs to set aside when I click (option + left arrow) which is a standard key binding to skip one word back while editing a document so when I am using overleaf or google docs and I suddenly click those buttons everything closes and goes to set side mode .
Is there a way I can change this key binding ?

### Environment
Please provide the following information:
 - Operating System:Mac os 10.15.6
 - Browser: Microsoft Edge Version 84.0.522.40
 - Extension version: 1.6

**Comment by XFox111** [comment]
Hi. Thanks for your feedback!
Unfortunately, I have no Mac so I couldn't determine which default shortcut binding will suit better. For Windows I've set default binding as `Alt+Left` for setting tabs aside and `Alt+P` for toggling the panel. So apparently, it binds as `Command+Left` in MacOS. To change default key bindings you can go to `chrome://extensions/shortcuts`

Also, I'd like to know which key bindings are more suitable for your OS so I can make them as default in future releases?

**Comment by saching13** [comment]
got it. thanks.

![image](https://user-images.githubusercontent.com/43363595/87985780-04ee0d80-ca91-11ea-9111-bf2827b3f426.png)

Here. this is the default config on mac: it is (option + left) and (option + p)

Mac has a key binding for cmd/option + all the arrows which is helpful for editing text and cmd+shift+t allows me to recover recently closed tab so For set aside tab I would suggest (cmd+shift+p or option+shit+p) and to toggle the set aside tab (option + p) seems good to me.  Hope this helps :)

**Comment by XFox111** [comment]
Hi. I've updated shortcuts. Is it ok now?
```
Default: Alt+Left, Alt+P
MacOS: Command+Shift+Left, Command+Shift+P
```

**Comment by saching13** [comment]
(cmd or options or ctrl) + (arrows) / (cmd or options or ctrl) + shift + (arrows)

all these have predefined to deal with jumping/selecting word/sentence depending on option or cmd button. I would suggest not to use them.

**Comment by XFox111** [comment]
Ok. I see. So what should I use instead? What key binding is more suitable in your opinion?

**Comment by saching13** [comment]
This is what I think would be better.
`set tab aside: option + P  // since it is not a trivial operation that might send all your tabs to set tab aside by mistake if you press them instead of print(cmd +p)
 set current tab aside: cmd + shift + p // this way I don't think you can set them aside by mistake and also has a good reach of keys`

**Comment by XFox111** [comment]
Actually, available actions are a bit different. They are:
- Set all tabs aside (Alt+Left for Windows)
- Open/Close the panel (Alt+P for Windows)

So there's no "set current tab aside" action. That's why I use such keys (P is for Panel and Left arrow is for movement direction of tabs being closed)

**Comment by saching13** [comment]
set all tabs aside is named as set current tabs aside in the extension key bindings. my bad for not using right words. I understand why it was option + left. if that is the case then why not use `ctrl + T` this has no bindings. I just tested it.

**Comment by XFox111** [comment]
Ctrl+T opens a new tab

**Comment by saching13** [comment]
that is cmd + T in mac.

**Comment by XFox111** [comment]
Ok then

**Comment by saching13** [comment]
thanks alot.

**Comment by XFox111** [comment]
Hi. Just to make sure. `Command+T` for settings tabs aside and `Command+Shift+P` for closing/opening the pane is ok for you, right?

**Comment by saching13** [comment]
Not `cmd + T` use `ctrl + T` for mac.  `cmd + T` is for new tab in mac. I told this in last message.

**Comment by XFox111** [comment]
> that is cmd + T in mac.

Oh, I'm so sorry. I just didn't get this. I thought that ctrl+T IS a cmd+T in mac and it does not open a new tab. My bad ¯\_(ツ)_/¯

So `MacCtrl+T` for setting tabs aside and `Command+Shift+P` for closing/opening the pane?

**Comment by saching13** [comment]
yup. sounds perfect. Thanks

**Comment by XFox111** [comment]
Thanks for using my extension. I appreciate it) 

I've just done a new version and submitted it to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin) and [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd). It will take some time to pass the validation process. For now, you can download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version
