### ISSUE TITLE
Saved tabs are gone after policy update

### ISSUE THREAD

**Issue by espetro** [XFox111/ChromiumTabsAside#4]
I've just updated the new extension policy, which unabled the extension to be used. After accepting it, I went to the saved tabs history and OH! all of them were gone.

How do I recover them?

EDIT: It seems the version displayed is 1.0 but the extension is on 1.2

![proof](https://i.imgur.com/yySlIZJ.png)

**Comment by XFox111** [comment]
Yeah. I've noticed this some days ago, but I've thought that it's only my problem (sometimes I break everything when developing). So now I remember where I messed up. I'll fix it today
