### ISSUE TITLE
Add option to ignore pinned tabs

### ISSUE THREAD

**Issue by bogdan-calapod** [XFox111/ChromiumTabsAside#6]
Firstly, great extension, perfect replacement for old Edge's Set Aside :D 

The only thing that kind of bugs me is that it also grabs pinned tabs. It would be great to have the option to keep (ignore) pinned tabs when saving/restoring a group.

**Comment by XFox111** [comment]
Thanks for using my extension. I appreciate it) 

I've just fixed the issue and submitted the new version to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin) and [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd). It will take some time to pass the validation process. For now, you can download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version
