### ISSUE TITLE
Exclude setting aside New Tab page and other browser's builtin pages

### ISSUE THREAD

**Issue by miguedevel** [XFox111/ChromiumTabsAside#8]
I'm using the extension on Edge and the New Tab page (edge://newtab) is getting saved on a set aside set. In fact any builtin tab (that start with edge:// URL) is getting saved and I don't think they should be saved. I would also argue that extension tabs shouldn't be saved either but there might be cases/extensions where it is desired.

**Comment by XFox111** [comment]
I know. It's supposed to save them. But maybe I should consider excluding a new page. I really does have no point to be saved. But other built-it tabs still may be saved on purpose. For example, I want extensions tab to be saved when I left work on the extension because it has some tools I need.
So, I can exclude only new page. Is it ok?

**Comment by miguedevel** [comment]
Yeah, excluding new page only is fine.

**Comment by XFox111** [comment]
Thanks for using my extension. I appreciate it) 

I've just done a new version and submitted it to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin) and [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd). It will take some time to pass the validation process. For now, you can download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version
